"""Initial schema with all models

Revision ID: 843d992771f6
Revises:
Create Date: 2026-02-08 14:30:18.687026

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "843d992771f6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasets_name"), "datasets", ["name"], unique=True)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("doc_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_document_checksum", "documents", ["checksum"], unique=False)
    op.create_index("idx_document_content_type", "documents", ["content_type"], unique=False)
    op.create_index(op.f("ix_documents_checksum"), "documents", ["checksum"], unique=True)
    op.create_index(op.f("ix_documents_content_type"), "documents", ["content_type"], unique=False)
    op.create_table(
        "system_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_system_prompt_active", "system_prompts", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_system_prompts_is_active"), "system_prompts", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_system_prompts_version"), "system_prompts", ["version"], unique=True)
    op.create_table(
        "tool_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tools_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tool_prompt_active", "tool_prompts", ["is_active"], unique=False)
    op.create_index(op.f("ix_tool_prompts_is_active"), "tool_prompts", ["is_active"], unique=False)
    op.create_index(op.f("ix_tool_prompts_version"), "tool_prompts", ["version"], unique=True)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("system_prompt_id", sa.Integer(), nullable=False),
        sa.Column("tool_prompt_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "failed", name="session_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["system_prompt_id"],
            ["system_prompts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_prompt_id"],
            ["tool_prompts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("system", "user", "assistant", "tool", name="message_role"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=200), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_message_session_sequence", "messages", ["session_id", "sequence"], unique=False
    )
    op.create_index(op.f("ix_messages_role"), "messages", ["role"], unique=False)
    op.create_index(op.f("ix_messages_tool_call_id"), "messages", ["tool_call_id"], unique=False)
    op.create_table(
        "traces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("tool_version", sa.String(length=50), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("success", "failed", "timeout", name="trace_status"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("trace_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trace_prompt_version", "traces", ["prompt_version"], unique=False)
    op.create_index("idx_trace_session", "traces", ["session_id"], unique=False)
    op.create_index("idx_trace_status", "traces", ["status"], unique=False)
    op.create_index(op.f("ix_traces_prompt_version"), "traces", ["prompt_version"], unique=False)
    op.create_index(op.f("ix_traces_session_id"), "traces", ["session_id"], unique=True)
    op.create_index(op.f("ix_traces_status"), "traces", ["status"], unique=False)
    op.create_index(op.f("ix_traces_tool_version"), "traces", ["tool_version"], unique=False)
    op.create_table(
        "dataset_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.Integer(), nullable=True),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["traces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_datasetcase_dataset", "dataset_cases", ["dataset_id"], unique=False)
    op.create_index("idx_datasetcase_trace", "dataset_cases", ["trace_id"], unique=False)
    op.create_index(
        op.f("ix_dataset_cases_dataset_id"), "dataset_cases", ["dataset_id"], unique=False
    )
    op.create_index(op.f("ix_dataset_cases_trace_id"), "dataset_cases", ["trace_id"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.Integer(), nullable=False),
        sa.Column("judgment", sa.Enum("pass", "fail", name="evaluation_judgment"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["traces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluation_error_type", "evaluations", ["error_type"], unique=False)
    op.create_index("idx_evaluation_judgment", "evaluations", ["judgment"], unique=False)
    op.create_index("idx_evaluation_trace", "evaluations", ["trace_id"], unique=False)
    op.create_index(op.f("ix_evaluations_error_type"), "evaluations", ["error_type"], unique=False)
    op.create_index(op.f("ix_evaluations_judgment"), "evaluations", ["judgment"], unique=False)
    op.create_index(op.f("ix_evaluations_trace_id"), "evaluations", ["trace_id"], unique=False)
    op.create_table(
        "message_documents",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("message_id", "document_id"),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("tool_call_id", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "success", "failed", name="tool_call_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_toolcall_message", "tool_calls", ["message_id"], unique=False)
    op.create_index("idx_toolcall_name", "tool_calls", ["name"], unique=False)
    op.create_index("idx_toolcall_status", "tool_calls", ["status"], unique=False)
    op.create_index(op.f("ix_tool_calls_name"), "tool_calls", ["name"], unique=False)
    op.create_index(op.f("ix_tool_calls_status"), "tool_calls", ["status"], unique=False)
    op.create_index(
        op.f("ix_tool_calls_tool_call_id"), "tool_calls", ["tool_call_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_calls_tool_call_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_status"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_name"), table_name="tool_calls")
    op.drop_index("idx_toolcall_status", table_name="tool_calls")
    op.drop_index("idx_toolcall_name", table_name="tool_calls")
    op.drop_index("idx_toolcall_message", table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_table("message_documents")
    op.drop_index(op.f("ix_evaluations_trace_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_judgment"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_error_type"), table_name="evaluations")
    op.drop_index("idx_evaluation_trace", table_name="evaluations")
    op.drop_index("idx_evaluation_judgment", table_name="evaluations")
    op.drop_index("idx_evaluation_error_type", table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_dataset_cases_trace_id"), table_name="dataset_cases")
    op.drop_index(op.f("ix_dataset_cases_dataset_id"), table_name="dataset_cases")
    op.drop_index("idx_datasetcase_trace", table_name="dataset_cases")
    op.drop_index("idx_datasetcase_dataset", table_name="dataset_cases")
    op.drop_table("dataset_cases")
    op.drop_index(op.f("ix_traces_tool_version"), table_name="traces")
    op.drop_index(op.f("ix_traces_status"), table_name="traces")
    op.drop_index(op.f("ix_traces_session_id"), table_name="traces")
    op.drop_index(op.f("ix_traces_prompt_version"), table_name="traces")
    op.drop_index("idx_trace_status", table_name="traces")
    op.drop_index("idx_trace_session", table_name="traces")
    op.drop_index("idx_trace_prompt_version", table_name="traces")
    op.drop_table("traces")
    op.drop_index(op.f("ix_messages_tool_call_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_role"), table_name="messages")
    op.drop_index("idx_message_session_sequence", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_tool_prompts_version"), table_name="tool_prompts")
    op.drop_index(op.f("ix_tool_prompts_is_active"), table_name="tool_prompts")
    op.drop_index("idx_tool_prompt_active", table_name="tool_prompts")
    op.drop_table("tool_prompts")
    op.drop_index(op.f("ix_system_prompts_version"), table_name="system_prompts")
    op.drop_index(op.f("ix_system_prompts_is_active"), table_name="system_prompts")
    op.drop_index("idx_system_prompt_active", table_name="system_prompts")
    op.drop_table("system_prompts")
    op.drop_index(op.f("ix_documents_content_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_checksum"), table_name="documents")
    op.drop_index("idx_document_content_type", table_name="documents")
    op.drop_index("idx_document_checksum", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_datasets_name"), table_name="datasets")
    op.drop_table("datasets")
    # ### end Alembic commands ###
